version: "3.9"

services:
  # Mysql
  mysql:
    image: mysql:8.0.31
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      DATABASE_URL: $DATABASE_URL
      TZ: $TZ
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    # DBの疎通テスト
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    # ゾンビプロセス対策
    # https://docs.docker.jp/engine/reference/run.html#init
    init: true

  # Apollo Server
  apollo:
    build:
      # .でdocker-compose.ymlと同じフォルダにDockerfileがあることを示す
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APOLLO_PORT}:${APOLLO_PORT}
    environment:
      DATABASE_URL: $DATABASE_URL
    # DBのマイグレーションとデータ注入と開発サーバーの立ち上げ
    command: sh -c "npx prisma migrate dev && npx prisma db seed && npm run dev"
    volumes:
      # 開発環境では全てのファイルをバインドマウントする（ホストでもコンテナでも好きなほうで開発してください）
      # 下を参考に再度設定する
      # https://zenn.dev/dove/articles/d02f66cc0aa5c3#%E7%B5%90%E5%B1%80%E3%81%A9%E3%82%8C%E3%81%8C%E3%81%84%E3%81%84%E3%81%AE%E3%81%8B
      - .:/app
    # ゾンビプロセス対策
    # https://docs.docker.jp/engine/reference/run.html#init
    init: true
    # services:mysql が立ち上がってDBの疎通テストに合格しているなら services:apollo を立ち上げる
    depends_on:
      mysql:
        condition: service_healthy
