service: apollo-lambda
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  httpApi:
    cors: true
functions:
  graphql:
    # Make sure your file path is correct!
    # (e.g., if your file is in the root folder use server.graphqlHandler )
    # The format is: <FILENAME>.<HANDLER>
    handler: src/server.graphqlHandler
    # ここがAPI Gatewayのルートに設定されるのでCORSに阻まれたら見たほうがよい
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /graphql
          method: ANY
# Omit the following lines if you aren't using TS!
plugins:
  - serverless-plugin-typescript
