service: apollo-lambda
useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  # API GatewayのCORS
  # https://www.serverless.com/framework/docs/providers/aws/events/http-api/
  httpApi:
    cors:
      allowedOrigins:
        - https://nextjs-boilerplate-two-rosy.vercel.app
      allowedHeaders:
        - Content-Type
        - Authorization
        - Cookie
      allowedMethods:
        - GET
        - POST
        - OPTIONS
      allowCredentials: true
functions:
  graphql:
    # Make sure your file path is correct!
    # (e.g., if your file is in the root folder use server.graphqlHandler )
    # The format is: <FILENAME>.<HANDLER>
    handler: src/server.graphqlHandler
    environment:
      NEXTAUTH_SECRET: ${env:NEXTAUTH_SECRET}
    # API Gatewayのルート(?)
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /graphql
          method: ANY
# Omit the following lines if you aren't using TS!
plugins:
  - serverless-plugin-typescript
